# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Biblio-Isis
version:      0.13
version_from: lib/Biblio/Isis.pm
installdirs:  site
requires:
    Carp:                          0
    File::Glob:                    0
    File::Spec:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
